/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TasksTasksProjectImport } from './routes/tasks/$tasksProject'

// Create/Update Routes

const TasksTasksProjectRoute = TasksTasksProjectImport.update({
  id: '/tasks/$tasksProject',
  path: '/tasks/$tasksProject',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks/$tasksProject': {
      id: '/tasks/$tasksProject'
      path: '/tasks/$tasksProject'
      fullPath: '/tasks/$tasksProject'
      preLoaderRoute: typeof TasksTasksProjectImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/tasks/$tasksProject': typeof TasksTasksProjectRoute
}

export interface FileRoutesByTo {
  '/tasks/$tasksProject': typeof TasksTasksProjectRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/tasks/$tasksProject': typeof TasksTasksProjectRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/tasks/$tasksProject'
  fileRoutesByTo: FileRoutesByTo
  to: '/tasks/$tasksProject'
  id: '__root__' | '/tasks/$tasksProject'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  TasksTasksProjectRoute: typeof TasksTasksProjectRoute
}

const rootRouteChildren: RootRouteChildren = {
  TasksTasksProjectRoute: TasksTasksProjectRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/tasks/$tasksProject"
      ]
    },
    "/tasks/$tasksProject": {
      "filePath": "tasks/$tasksProject.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
