/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TasksTasksCategoryImport } from './routes/tasks/$tasksCategory'

// Create/Update Routes

const TasksTasksCategoryRoute = TasksTasksCategoryImport.update({
  id: '/tasks/$tasksCategory',
  path: '/tasks/$tasksCategory',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks/$tasksCategory': {
      id: '/tasks/$tasksCategory'
      path: '/tasks/$tasksCategory'
      fullPath: '/tasks/$tasksCategory'
      preLoaderRoute: typeof TasksTasksCategoryImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/tasks/$tasksCategory': typeof TasksTasksCategoryRoute
}

export interface FileRoutesByTo {
  '/tasks/$tasksCategory': typeof TasksTasksCategoryRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/tasks/$tasksCategory': typeof TasksTasksCategoryRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/tasks/$tasksCategory'
  fileRoutesByTo: FileRoutesByTo
  to: '/tasks/$tasksCategory'
  id: '__root__' | '/tasks/$tasksCategory'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  TasksTasksCategoryRoute: typeof TasksTasksCategoryRoute
}

const rootRouteChildren: RootRouteChildren = {
  TasksTasksCategoryRoute: TasksTasksCategoryRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/tasks/$tasksCategory"
      ]
    },
    "/tasks/$tasksCategory": {
      "filePath": "tasks/$tasksCategory.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
